[package]
name = "utility_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
soroban-token-sdk = "21.7.6"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
